services:
  portfolio:
    container_name: ejemploContainerPortfolio
    image: nginx:alpine
    # Rutas. Asegure que los archivos están en la ruta especificada
    volumes:
     # la carpeta 'www' como directorio web del contenedor
      - ./www:/usr/share/nginx/html:ro  
      # Monta la configuración personalizada de Nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    ports:
      - '80'  # Solo expongo el puerto 80
    networks:
      - ejemploNetworks


networks:
  ejemploNetworks:
    external: true
